apiVersion: apps/v1
kind: Deployment
metadata:
  name: interact
  labels:
    app: interact
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interact
  template:
    metadata:
      labels:
        app: interact
    spec:
      containers:
      - image: zxcv9203/piscine-golang-interact:0.6.2
        name: interact
        #resources:
        #  limits:
        #    memory: 512Mi
        #    cpu: "1"
        #  requests:
        #    memory: 256Mi
        #    cpu: "0.2"
        ports:
        - containerPort: 80
          name: interact-port

---
apiVersion: v1
kind: Service
metadata:
  name: interact-lb
spec:
  type: LoadBalancer
  selector:
    app: interact
  ports:
  - nodePort: 30689
    port: 80
    protocol: TCP
    targetPort: 80

